파티생성
nbbang-sinchon/frontend pull request #58
Opened 2022-02-22 07:02 UTC by joooonis

- 파티 생성 입니다. 
- 일단 hashtag는 임의로 보내도록 해두었습니다. 
- hashtag를 가져와서 array로 바꾸는 유틸에 문제가 있는거 같기도 합니다.

2022-02-22 07:47 UTC, korung3195 requested changes
고생하셨습니다!
어쩌다보니 칭찬보다는 피드백을 많이 남긴 것 같은데... 모쪼록 부드럽게 받아들여주세요

2022-02-22 07:47 UTC, korung3195 commented on src/components/NewParty.jsx
>      <>
이렇게 빈 태그를 넣는 이유는 같은 레벨에 여러 노드가 있으면 리액트에서 에러가 발생하기 때문이에요
예를들어
```
return (
  <div></div>
  <div></div>
  <div></div>
)
```
이러면 오류가 발생하기 때문에 빈 태그로 감싸줘야합니다.
근데 여기의 경우는 <Container> 노드 하나만 return 하기 때문에 빈 태그가 필요하지 않을 것 같아요

2022-02-22 07:47 UTC, korung3195 commented on src/components/PartyFilter.jsx
> +export default PartyFilter;
이 파일이 아직도 남아있다는건 최신 dev가 반영되지 않은 것 같습니다 ㅜㅜ
충돌이 발생했을 때 잘못 반영하신 것 같아요

2022-02-22 07:47 UTC, korung3195 commented on src/components/NewParty.jsx
>  export { NewPartyHeader, NewParty };
제 생각에 한 파일에 두 개의 컴포넌트를 정의하는건 조금 보기 불편할 것 같습니다.
안그래도 css 때문에 코드가 길어지는걸요ㅠㅠ

2022-02-22 07:47 UTC, korung3195 commented on src/components/NewParty.jsx
>        </Container>
지금 새 파티 정보를 입력하는 방식이 div 안에 input들이 존재하게 짜셨는데요,
이 부분을 form을 이용해서 바꿔보는건 어떨까 싶습니다.
그렇게 하면 장점이
1. <form> 이라는 분명한 태그로 노드의 의미를 분명하게 전달할 수 있다 (semantic tag)
2. form에는 submit event가 발생해서 내부의 input data를 더 쉽게 파싱할 수 있다
3. 따라서 onChange 함수를 사용하지 않을 수 있다.  => onChange는 내부 value가 변할때마다 state를 변화시키므로 매번 랜더링이 다시 발생한다 => 매우 비효율적 => 확인을 누를때 한번에 검사할 수 있는 onSubmit이 더 나음

form 태그를 사용한 예시는 Header 컴포넌트 내부의 검색창을 보시면 좋을 것 같습니다!

2022-02-22 07:51 UTC, joooonis commented on src/components/NewParty.jsx
>  export { NewPartyHeader, NewParty };
맞습니다. 이번에 하다보니 저도 좀 그렇게 느꼈습니다..!

2022-02-22 07:56 UTC, joooonis commented on src/components/NewParty.jsx
>      <>
그렇군요!

2022-02-22 07:56 UTC, joooonis commented on src/components/NewParty.jsx
>        </Container>
자세히 봐주셔서 감사합니다! 사실 form 사용을 고려 안 한 건 아닌데요..! 헤더 컴포넌트와 input들이 들어있는 뉴파티 컴포넌트가 서로 분리되어 있어서 submit event를 헤더의 버튼에서 감지하는데 인풋input들은 뉴파티 컴포넌트에 있어서요 이런 경우에도 form이 작동이 잘 될까요?

2022-02-22 08:04 UTC, joooonis commented on src/components/PartyFilter.jsx
> +export default PartyFilter;
허걱 그러고보니 두번째 풀리퀘 하고 풀을 안 했네요

2022-02-22 08:21 UTC, korung3195 commented on src/components/NewParty.jsx
>        </Container>
그런 사정이 있었군요... 더 나은 구조가 있을 것 같기는 하지만 일단 지금 상태에서 해결 방법을 말씀드리자면 `useRef` 를 이용하는 겁니다!

```
<NewPartyPage>
  <NewPartyHeader />
  <NewParty />
</NewPartyPage>
```

이 상태라고 가정했을 때, 각 컴포넌트에서 해야할 일을 정리해드리면

- NewPartyPage
 1. useRef 훅을 이용해  를 이용해 새로운 ref를 생성 `const formRef = useRef()`
 2. NewPartyHeader, NewParty 모두에 formRef를 props로 전달

- NewPartyHeader
 1. 완료 버튼의 onClick 리스너로 form에 submit 이벤트를 발생시키는 함수를 달아둠 
    (ex. `onClick={()=>formRef.current.submit()}`)
 
- NewParty
 1. input들을 감싸는 form을 지정하고 ref를 달아둠 `<form ref={formRef} />`
 2. form의 onSubmit 리스너를 정의함

예외 처리라던가 입력값 검증같은 것도 추가로 생각해야하지만 일단 대략적인 구조는 이렇습니다.
useRef는 매우 중요한 훅이니까 이 기회에 써보시는 것도 아주 좋아보입니다. 
그리고 useRef에 대해 학습한 내용을 docs에 남겨주시면 더욱 좋을 것 같습니다 ㅎㅎ
여기서 useRef는 아직 랜더링되지 않은 HTML element를 가리키는 일종의 포인터 역할로 사용된다고 보시면 됩니다.
추가로 질문있으시면 해주세요!

2022-02-22 08:25 UTC, joooonis commented on src/components/NewParty.jsx
>        </Container>
우아 너무 좋습니다~! 피드백이 너무 도움이 많이 되네요~

2022-02-25 07:57 UTC, joooonis commented on src/components/NewParty.jsx
> +  const formRef = useRef();
useRef를 사용하여 form를 가리키게 하였습니다.

2022-02-25 07:57 UTC, joooonis commented on src/components/NewParty.jsx
> +    };
완료 버튼을 누르면 form 내부에 입력된 값을 가지고 newParty 객체를 만듭니다.

2022-02-25 07:58 UTC, joooonis commented on src/components/NewParty.jsx
> +      hashtags: hashTagStringToList(form.get('hashtags')),
띄어쓰기를 기준으로 해시테그를 리스트로 반환합니다.
ex) 뿌링클 야식 치킨 -> ["뿌링클", "야식", "치킨"]

2022-02-25 08:03 UTC, joooonis commented
form 과 submit 이벤트를 함께 사용하여고 싶었으나 

  `onClick={()=>formRef.current.submit()}`
을 사용하여 전달한 submit 이벤트에 대하여 
  `event.preventDefault()` 
가 적용이 되지를 않아 계속해서 새로고침이 되었습니다. 그래서 `formRef`로 form을 가리키는 것은 잘 되어서 click 이벤트에서 처리를 하는 것으로 로직을 구현하였습니다.

2022-02-25 09:36 UTC, korung3195 commented
그렇군요 방법을 찾으셔서 다행이네요!
고생하셨습니다

2022-02-25 13:16 UTC, merged